<a href="https://colab.research.google.com/github/chayhuixiang/tensorflow-starter/blob/main/1%20-%20Numpy%20Crash%20Course/1_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1.1.1: Numpy Arrays

In [ ]:
import numpy as np

In [ ]:
# Convert existing list to numpy array
myList = [1,2,3]
np.array(myList)

In [ ]:
# Convert existing nested list to numpy array
nested_list = [[1,2],[3,4],[5,6]]
np.array(nested_list)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [ ]:
# Making a range of numbers
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# Range of zeros
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
# Range of ones
np.ones((3,4))*3

array([[3., 3., 3., 3.],
       [3., 3., 3., 3.],
       [3., 3., 3., 3.]])

In [ ]:
# Number of values we want in an interval, INCLUSIVE OF START AND STOP POINT
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [ ]:
# Creating identity matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
# Getting random numbers
np.random.rand(2)

array([0.63839879, 0.33186882])

In [ ]:
# Getting random matrix, pass in the shape we want
np.random.rand(3,4)

array([[0.82304927, 0.44728972, 0.58819763, 0.69869473],
       [0.34989926, 0.83559082, 0.89609634, 0.48333435],
       [0.42089512, 0.68522165, 0.9506168 , 0.09330569]])

In [ ]:
# Random values from standard distribution
np.random.randn(5,5)

array([[-1.09662972,  1.24835171,  0.2233015 , -0.55633322, -0.1644965 ],
       [ 0.41413757, -0.72132959,  1.10771182, -0.01905381,  1.01664131],
       [-1.45576416,  0.40373197,  1.01864172,  1.45125559, -0.8957325 ],
       [ 1.0470061 , -0.33522876, -0.14833195, -0.3303872 , -0.89173778],
       [-0.00968605,  0.07509258, -0.55427337, -0.48549114, -1.31556666]])

In [ ]:
# random int, random matrix, pass in the shape we want 
np.random.randint(1,100,(2,3))

array([[62, 40, 14],
       [74,  8, 66]])

In [ ]:
# Standardise the random numbers we have
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [ ]:
arr = np.arange(25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [ ]:
ranarr = np.random.randint(0,50,10)
ranarr

array([21, 43, 24, 48, 26, 41, 27, 15, 14, 46])

In [ ]:
# Reshaping arrays
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [ ]:
# Max value in array
ranarr.max()

48

In [ ]:
# Index of max value in array 
ranarr.argmax()

3

In [ ]:
# Min value in array
ranarr.min()

14

In [ ]:
# Index of min value in array 
ranarr.argmin()

8

In [ ]:
# Data type of array
ranarr.dtype

dtype('int64')

In [ ]:
myarr = np.random.rand(4)
myarr.dtype

dtype('float64')

# 1.1.2: Numpy Index Selection

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
# Exact same indexing syntax as python lists
arr[8]

8

In [ ]:
arr[1:5]

array([1, 2, 3, 4])

In [ ]:
arr[:5]

array([0, 1, 2, 3, 4])

In [ ]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [ ]:
# Set multiple values inside numpy array, CANT BE DONE IN VANILLA PYTHON
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [ ]:
# Array slicing, same as python
arr = np.arange(0,11)
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [ ]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [ ]:
# Alters the original array, slice of array points to original array
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
# Prevent array from pointing to original array, use copy() to copy the array
arr_copy = arr.copy()[:] = 100
arr_copy

100

In [ ]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [ ]:
# 2d indexing
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [ ]:
arr_2d.shape

(3, 3)

In [ ]:
# Gets the 3rd row
arr_2d[2]

array([35, 40, 45])

In [ ]:
# 2d indexing
arr_2d[0,2]

15

In [ ]:
# 2d slicing
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [ ]:
# Boolean maths
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
arr > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [ ]:
arr[arr > 4]

array([ 5,  6,  7,  8,  9, 10])

## Numpy indexing

<img src='https://drive.google.com/uc?id=1jBseUXEqcMj1nmTRnpYOO2fdBkTBXoD2'>

# 1.1.3: Numpy Operations

In [ ]:
# Normal Operations to a numpy array applies to all the elements of the array
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [ ]:
# Add two arrays of the same shape
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
# Division by zero in numpy
arr / arr

# Warning comes out, gives nan result

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
# Square root
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [ ]:
# Trigo
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [ ]:
# Log
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [ ]:
# Get sum of array
arr.sum()

45

In [ ]:
# Get mean of array
arr.mean()

4.5

In [ ]:
# Get variance of array
arr.var()

8.25

In [ ]:
# Get std deviation of array
arr.std()

2.8722813232690143

In [ ]:
# Working with 2d arrays
arr2d = np.arange(0,25).reshape(5,5)

In [ ]:
# Perform operation across rows, which gets the sum of columns
arr2d.sum(axis=0)

array([50, 55, 60, 65, 70])

In [ ]:
# Perform operation across columns, which gets the sum of rows
arr2d.sum(axis=1)

array([ 10,  35,  60,  85, 110])

## Axis Logic


<img src='https://drive.google.com/uc?id=13Qay_QYGsb3rbud1kmuz4ClQRUvczeW1'>

# 1.1.4: Numpy Exercises

In [ ]:
# Import Numpy as np
import numpy as np

In [ ]:
# Create an array of 10 zeros
arr = np.zeros(10)
arr

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
# Create an array of 10 ones
arr = np.ones(10)
arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
# Create an array of 10 fives
arr = np.ones(10)*5
arr

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [ ]:
# Create an array of integers from 10 to 50
arr = np.arange(10,51)
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [ ]:
# Create an array of all the even integers from 10 to 50
arr = np.arange(10,51,2)
arr

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [ ]:
# Create a 3x3 matrix with values ranging from 0 to 8
arr = np.arange(0,9).reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# Create a 3x3 identity matrix
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# Use NumPy to generate a random number between 0 and 1
random = np.random.rand()
random

0.3811212942848594

In [ ]:
# Array of random 25 numbers sampled from normal distribution
arr = np.random.rand(25)
arr

array([0.34448512, 0.64178884, 0.15612004, 0.59351601, 0.83014954,
       0.90290318, 0.8827698 , 0.58073629, 0.54617823, 0.51310989,
       0.9209838 , 0.86867789, 0.72119158, 0.12395274, 0.22920597,
       0.07560446, 0.50568841, 0.12670969, 0.01393038, 0.33207784,
       0.51761845, 0.39391133, 0.29073298, 0.01600454, 0.25805542])

In [ ]:
# Create a floating matrix from 0.01 to 1
arr = np.arange(1,101).reshape(10,10)/100
arr

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [ ]:
# Create an array of 20 linearly spaced points between 0 and 1
arr = np.linspace(0,1,20)
arr

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
mat = np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# 2d indexing
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [ ]:
mat[3,4]

20

In [ ]:
mat[:3,1]

array([ 2,  7, 12])

In [ ]:
mat[4]

array([21, 22, 23, 24, 25])

In [ ]:
mat[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [ ]:
# Sum of all values in mat
mat.sum()

325

In [ ]:
# Std Dev of all values in mat
mat.std()

7.211102550927978

In [ ]:
# Sum of all the columns in mat
mat.sum(axis=0)

array([55, 60, 65, 70, 75])